<?php
/**
 * @file
 * Code for the administration page.
 */


/**
 * A Drupal form function providing the administration form for this module.
 *
 * @param array $form
 *   The Drupal form definition.
 * @param array &$form_state
 *   The Drupal form state.
 *
 * @return array
 *   The Drupal form definition.
 */
function islandora_owner_permissions_admin_form($form, &$form_state) {
  return array();
}

/**
 * The submit function for the administration form.
 *
 * @param array $form
 *   The Drupal form definition.
 * @param array &$form_state
 *   The Drupal form state.
 */
function islandora_owner_permissions_admin_form_submit($form, &$form_state) {
}
